[workspace]
resolver = "2"

members = [
    "tableturf",
    "tableturf-client",
    "tableturf-server",
]

[workspace.dependencies]
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
color-eyre = "0.6.3"
